연습문제

주사위는 1부터 6까지의 숫자를 가진다. 이를 100번 던져서 나오는 숫자를 넘파이 난수를 발생시켜서 시뮬레이션하고 나오는 숫자의 평균을 구하라.

In [3]:
import random
import numpy as np

In [10]:
random.seed(0)
k = [np.random.randint(1, 7) for _ in range(100)]
np.mean(k)

3.66

연습문제

In [14]:
a = np.array(range(1, 7)).reshape(2,3)
b = np.array(range(7, 13)).reshape(2,3)
a+b

array([[ 8, 10, 12],
       [14, 16, 18]])

연습문제

In [15]:
a = np.arange(1,10)
a*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

연습문제

In [16]:
a = np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [17]:
a = np.arange(50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [25]:
a = np.array(['' for _ in range(27)], dtype='<U10')
a.reshape(3, 3, 3)

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [26]:
np.zeros((3, 3, 3), dtype='<U10')

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

full() 메서드로 하나의 특정 값으로 배열을 채울 수 있다.

In [28]:
np.full((3, 3, 3), 'playdata')

array([[['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']]], dtype='<U8')

In [37]:
np.array(range(2, 41, 2)).reshape((2, 2, 5))

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

선형대수학에서 단위 행렬(identity matrix)는 주대각의 원소가 모두 1이며 나머지 원소는 모두 0인 정사각 행렬이다. np.eye(n)를 이용해서 만들 수 있다.

In [46]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
np.random.seed(0)
np.array(np.random.randint(0, 2, 9)).reshape(3, 3).astype(dtype= 'bool')

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [53]:
np.random.seed(0)
k = np.random.rand(10)*10
k.astype('int')

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3])

In [55]:
k = np.ones((10, 10))
k[1:-1, 1:-1] = 0
k

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [77]:
k = np.ones((10, 10))
k[[0,-1], :] = 0
k[:, [0,-1]] = 0
k

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [78]:
k = np.ones((8, 8))
for i in range(8):
    for j in range(8):
        if (i+j)%2!=0:
            k[i, j]=0
k

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [87]:
k = np.ones((8,8)).astype('i')
k[0::2, 1::2] = 0
k[1::2, 0::2] = 0
k

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int32)

In [88]:
k = np.eye(2)
np.tile(k, (4, 4))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

같은 shape과 len의 bool type 어레이로 인덱싱 할 수 있다. 해당 위치에 대해 True면 값을 반환하고 False면 반한하지 않는다.

In [110]:
k = np.arange(11)
k[((3<k) & (k<7))] *= -1
k

array([ 0,  1,  2,  3, -4, -5, -6,  7,  8,  9, 10])

In [109]:
sum(np.arange(101)[np.arange(101)%3==0])

1683

In [116]:
np.linspace(1, 9, 9)/10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [190]:
while True:
    try:
        n = int(input("자연수만 입력해주세요."))
        if n<=0:
            continue;
        k = [np.random.choice(range(1, 46), size=6, replace=False) for _ in range(n)]
        display(np.sort(k))
        break;
    except ValueError:
        continue;

자연수만 입력해주세요. 5


array([[ 3, 15, 16, 20, 32, 40],
       [ 1, 12, 15, 30, 32, 42],
       [ 5, 18, 26, 30, 34, 35],
       [ 2, 15, 22, 23, 26, 39],
       [ 4, 11, 22, 34, 37, 43]])

In [174]:
resp_time = np.array([158, 85, 205, 24, 42, 175, 188, 149, 153, 171, 137, 55, 108,
199, 177, 209, 218, 76, 103, 189, 110, 192, 136, 119, 4, 102,
177, 212, 110, 37, 163, 32, 77, 22, 125, 184, 46, 139, 72,
168, 133, 209, 148, 47, 102, 65, 160, 56, 11, 96, 169, 118,
55, 135, 217, 49, 100, 85, 179, 15, 139, 199, 124, 142, 15,
49, 168, 171, 168, 177, 147, 23, 199, 26, 51, 42, 90, 128,
186, 169, 129, 70, 198, 111, 81, 150, 17, 177, 201, 10, 75,
199, 55, 151, 183, 152, 119, 193, 110, 204])
len(resp_time[resp_time>200])

8

In [185]:
np.quantile(resp_time, 0.75)

175.5

In [188]:
p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
0, 1])

m, n = np.unique(result, return_counts=True)
print(p[np.argmax(n)])

뽀로로
